# Generated by Django 6.0.5 on 2026-06-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('participants', models.JSONField(default=list)),
                ('meeting_date', models.DateTimeField()),
                ('transcript', models.JSONField(default=list)),
                ('analysis', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meetings',
                'ordering': ['-created_at'],
            },
        ),
    ]
